name: Execução de Testes E2E - Cielo 🚀

# Define quando o pipeline será executado
on:
  push:
    branches: [ "main", "master" ] # Roda sempre que você enviar código para essas branches
  pull_request:
    branches: [ "main", "master" ] # Roda quando alguém abrir um Pull Request
  workflow_dispatch: # Permite rodar manualmente pelo botão no site do GitHub

jobs:
  tests-e2e:
    runs-on: ubuntu-latest # Usa uma máquina Linux gratuita do GitHub

    steps:
      # 1. Faz o download do código do seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Configura o Node.js e gerencia o cache do npm automaticamente na raiz
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'

      # 3. Instala as dependências e roda os testes do Cypress (tudo na raiz)
      - name: Instalar dependências e Rodar Testes Cypress
        uses: cypress-io/github-action@v6
        with:
          command: npm run cypress:run

      # 4. Salva os prints de tela na rota padrão caso algum teste falhe
      - name: Salvar Screenshots em caso de falha
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots